version: '3.8'

networks:
  integration-test-example:

services:
  app:
    image: app:latest
    volumes:
      - /app
    working_dir: /app
    ports:
      - "8888:8080"
    environment:
       DATABASE_URL: jdbc:postgresql://posttestdb:5432/postgres
    networks:
      - integration-test-example
    command: ["java", "-jar", "build/libs/posttest-0.0.1-SNAPSHOT.jar"]
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres

    container_name: posttestdb
    restart: on-failure
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - integration-test-example